// <auto-generated />
using System;
using HashiCorpIntegration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HashiCorpIntegration.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250904120815_ProductChanged")]
    partial class ProductChanged
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HashiCorpIntegration.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sports & Outdoors"
                        });
                });

            modelBuilder.Entity("HashiCorpIntegration.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 9, 4, 12, 8, 14, 983, DateTimeKind.Utc).AddTicks(4944),
                            Description = "Latest model smartphone with advanced features.",
                            ImageUrl = "https://example.com/images/smartphone.jpg",
                            Name = "Smartphone",
                            Price = 699.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 9, 4, 12, 8, 14, 983, DateTimeKind.Utc).AddTicks(4946),
                            Description = "High-performance laptop for work and play.",
                            ImageUrl = "https://example.com/images/laptop.jpg",
                            Name = "Laptop",
                            Price = 999.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 9, 4, 12, 8, 14, 983, DateTimeKind.Utc).AddTicks(4948),
                            Description = "A thrilling science fiction novel set in a dystopian future.",
                            ImageUrl = "https://example.com/images/scifi_novel.jpg",
                            Name = "Science Fiction Novel",
                            Price = 19.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 9, 4, 12, 8, 14, 983, DateTimeKind.Utc).AddTicks(4949),
                            Description = "Comfortable cotton t-shirt available in various sizes.",
                            ImageUrl = "https://example.com/images/tshirt.jpg",
                            Name = "T-Shirt",
                            Price = 14.99m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 9, 4, 12, 8, 14, 983, DateTimeKind.Utc).AddTicks(4951),
                            Description = "Powerful kitchen blender for smoothies and more.",
                            ImageUrl = "https://example.com/images/blender.jpg",
                            Name = "Blender",
                            Price = 49.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2025, 9, 4, 12, 8, 14, 983, DateTimeKind.Utc).AddTicks(4952),
                            Description = "Non-slip yoga mat for all types of exercise.",
                            ImageUrl = "https://example.com/images/yoga_mat.jpg",
                            Name = "Yoga Mat",
                            Price = 29.99m,
                            StockQuantity = 150
                        });
                });

            modelBuilder.Entity("HashiCorpIntegration.Entities.Product", b =>
                {
                    b.HasOne("HashiCorpIntegration.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
